<a href="https://colab.research.google.com/github/caseymacelhiney/neuro265/blob/main/coding_homework_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Coding Homework #8

**Instructions**

1. Make a *Markdown Cell* that contains the following information:
- Your name (small header)
- The name of this class (italicized)
- The date (bolded)

2. Create a *Code Cell* that imports relevant modules - specifically, <code>numpy as np</code>, <code>matplotlib.pyplot as plt</code>, and <code>from scipy.stats import pearsonr</code>.

3. For this assignment, you will be working with the <code>fear_conditioning_traces_hw8.csv</code>, and <code>extinction_predictors_hw8.csv</code> files that I uploaded to our shared Google Drive folder. You will also be using the <code>shock_index.csv</code> and <code>tone_index.csv</code> files on our shared GitHub repo (we used these files to complete our in-class coding notebook on 4/12/23). Upload all of these files to your GitHub repo, and import them as <code>numpy</code> arrays named <code>fear_traces</code>, <code>extinction_predictors</code>, <code>shock_index</code>, and <code>tone_index</code>, respectively, in a *Code Cell*. **Important**: Make sure you that import <code>tone_index.csv</code> and <code>shock_index.csv</code> using the **exact** syntax that we used in our 4/12/23 in-class notebook - e.g., <code>np.loadtxt('', delimiter = ',').astype(int)</code>.

4. The <code>fear_conditioning_traces</code> array contains scaled (between 0 and 1) fluorescent traces from ROIs (individual cells) in the anterior cingulate cortex (ACC) of one mouse during **fear conditioning** and **fear extinction**. We went over fear conditioning in class - the mouse is presented with an auditory tone that coincides with a mild foot-shock. The mouse learns to associate the tone with the foot-shock, thereby forming a fear memory. This mouse underwent fear conditioning, and 48 hours later, was placed back into the conditioning chamber and presented with the auditory tone to assess how well it remembered the tone/foot-shock combination. The tone was presented a total of 22 times - eventually, as the tone is continuously presented without the foot-shock, the mouse begins to disassociate the tone and the foot-shock, and form a neutral extinction memory. The cells in your <code>fear_conditioning_traces</code> array were able to be stably imaged across both sessions, allowing us to compare how they react across fear memory formation and extinction.

5. In a new *Code Cell*, make two new variables - <code>conditioning_traces</code>, and <code>extinction_traces</code>. Your <code>fear_conditioning_traces</code> array contains ROIs (cells) in columns, and samples in rows. The first 10458 samples correspond to the conditioning session, and the remaining samples correspond to the extinction session. Your <code>conditioning_traces</code> array should contain the first 10458 samples (as rows), with ROIs (cells) as columns. Your <code>extinction_traces</code> array should contain the remaining (10459 through the final sample) samples (as rows), with ROIs (cells) as columns. 

6. In a new *Code Cell*, print the size of your <code>conditioning_traces</code> and <code>extinction_traces</code> arrays. 

7. In a new *Code Cell*, make <code>time_conditioning</code> and <code>time_extinction</code> variables, corresponding to time during the conditioning session, and time during the extinction session, respectively. The sampling rate for the miniscope used to capture these data was 15 fps. Use this information to make your variables, which should both start at "0", end at the total length of the recording session (in seconds), and have a length equal to the number of samples for each session.

8. In a new *Markdown Cell*, state the number of ROIs (cells) that were imaged during these sessions, and the total length of time, both in seconds, and in minutes, of the conditioning and extinction sessions.

9. In a new *Code Cell*, plot the first and second ROIs from your <code>conditioning_traces</code> variable in one subplot. Plot the first and second ROIs from your <code>extinction_traces</code> variable in a second subplot. Make the first ROI <font color = 'blue'>blue</font>, and the second ROI <font color = 'red'>red</font> in each subplot. Put time on the x-axis of both subplots. Make vertical black lines at shock onset (3 total), and vertical green lines at tone onset (3 total) in your first subplot. Label your axes.

10. In a new *Markdown Cell*, describe the relationship between the conditioning/extinction traces for your first ROI, and the conditioning/extinction traces for your second ROI. Does there seem to be a relationship between how a cell responds during conditioning, and how it responds during extinction?

11. To evaluate how each cell might respond during conditioning and extinction more formally, we're going to use generalized linear modeling (GLM). To do this, we're going to use shock onset and tone onset as predictors in our model for the conditioning session, and tone onset as predictors for another model for the extinction session. We'll correlate the actual traces and the predicted traces from these models, and compare correlation coefficients between the two sessions to see if there's a relationship. This will answer the question: If a cell responds more strongly to shocks/tones during conditioning, does it also respond more strongly to tones during extinction? In other words - are the cells that encode the tone/shock memory the same cells that form the extinction memory?

12. In a new *Code Cell*, make a <code>predictors_conditioning</code> variable that contains shock onset and tone onset. Reference our in-class notebook from 4/12/23 to do this - specifically, the *Code Cell* underneath the section that says **Modeling our Fear Data**. These are the same data that we used for this notebook, so you can use this exact code to re-create your <code>shock_array</code> and <code>tone_array</code> variables. Reference how we made the <code>predictors</code> variable for <code>model1</code> and <code>model3</code> in that notebook - you should have the same <code>predictors</code> variable as <code>model3</code> for your <code>predictors_conditioning</code> variable here (i.e., the two variables should be identical). 

13. We want to now run our model for each ROI in our <code>conditioning_traces</code> array, correlate the predicted trace vs. the actual trace, and store the correlation coefficient in a new variable called <code>r_model_conditioning</code>. To do this, reference the last *Code Cell* in our notebook from 4/12/23 - specifically, the subsection that says <code># For model 3</code>. You will need to first create your <code>r_model_conditioning</code> variable using <code>np.zeros</code> - remember that this time, we have more than 10 ROIs, so you will need to change the number inside of the parentheses. You will also need to change the number of times your loop runs from <code>for i in range(10)</code> to loop through all of the ROIs in your <code>conditioning_traces</code> array. In a new *Code Cell*, create your <code>r_model_conditioning</code> variable, and run your <code>for</code> loop. Each loop should extract an ROI from <code>conditioning_traces</code>, run <code>sm.GLM</code> between the trace and the <code>predictors</code> variable you created, fit the model, create a predicted trace, get a correlation coefficient using <code>pearsonr</code>, and store the correlation coefficient in a new column of <code>r_index_conditioning</code>.

14. In a new *Code Cell*, run another loop that does the same thing for your <code>extinction_traces</code> array. This time, you should make a variable called <code>r_index_extinction</code> to store your correlation coefficients. You should use your <code>extinction_predictors</code> variable as the predictor for your model (this contains values for tone onset during the extinction session). 

15. In a new *Code Cell*, use the <code>pearsonr</code> function to correlate your <code>r_index_conditioning</code> and <code>r_index_extinction</code> variables.

16. In a new *Code Cell*, make a <code>scatter</code> plot with <code>r_index_conditioning</code> on the x-axis, and <code>r_index_extinction</code> on the y-axis. Label your axes.

17. In a new *Markdown Cell*, interpret your results. Based on your correlation coefficient and scatter plot, does it seem like a cell that responds strongly to shock and tone onset during the conditioning session is more likely to respond strongly to tone onset during the extinction session?

18. Make sure to put a <code>#</code> in each *Code Cell* to describe what it does.

19. Save a copy of this notebook to your GitHub repo with the title <code>coding_homework_8.ipynb</code>.

##Casey MacElhiney
_Intro to Neural Data Anaylsis_

__April 3, 2023__

In [1]:
#Create a Code Cell that imports relevant modules - specifically, numpy as np, matplotlib.pyplot as plt, and from scipy.stats import pearsonr.
import numpy as np
import matplotlib.pyplot as plt
import scipy.stats as pearsonr

In [3]:
#For this assignment, you will be working with the fear_conditioning_traces_hw8.csv, and extinction_predictors_hw8.csv files that I uploaded to our shared Google Drive folder. 
#You will also be using the shock_index.csv and tone_index.csv files on our shared GitHub repo 
#(we used these files to complete our in-class coding notebook on 4/12/23). 
#Upload all of these files to your GitHub repo, and import them as numpy arrays named fear_traces, extinction_predictors,
#shock_index, and tone_index, respectively, in a Code Cell. I
#mportant: Make sure you that import tone_index.csv and shock_index.csv using the exact syntax that we used in our 4/12/23 in-class notebook - 
#e.g., np.loadtxt('', delimiter = ',').astype(int).
shock_index = np.loadtxt('https://raw.githubusercontent.com/hallockh/neur_265/main/shock_index.csv', delimiter = ',').astype(int)
tone_index = np.loadtxt('https://raw.githubusercontent.com/hallockh/neur_265/main/tone_index.csv', delimiter = ',').astype(int)
extinction_predictors = np.loadtxt('https://raw.githubusercontent.com/caseymacelhiney/neuro265/main/extinction_predictors_hw8.csv', delimiter=",")
fear_traces = np.loadtxt('https://raw.githubusercontent.com/caseymacelhiney/neuro265/main/fear_conditioning_traces_hw8.csv', delimiter=",")

In [4]:
fear_traces

array([[0.15983534, 0.41501203, 0.3902705 , ..., 0.35204699, 0.48097605,
        0.62691492],
       [0.16923594, 0.42458029, 0.41144669, ..., 0.34330168, 0.48668911,
        0.60960583],
       [0.16266296, 0.42059838, 0.41282583, ..., 0.3496634 , 0.50390474,
        0.60653214],
       ...,
       [0.10190191, 0.13573   , 0.10133815, ..., 0.37895831, 0.42750513,
        0.44738347],
       [0.10574757, 0.16318269, 0.11586664, ..., 0.38334589, 0.41140551,
        0.44590861],
       [0.09936723, 0.14104242, 0.11517277, ..., 0.39657268, 0.41661691,
        0.4648573 ]])

In [10]:
#In a new Code Cell, make two new variables - conditioning_traces, and extinction_traces. 
#Your fear_conditioning_traces array contains ROIs (cells) in columns, and samples in rows. 
#The first 10458 samples correspond to the conditioning session, and the remaining samples correspond to the extinction session. 
#Your conditioning_traces array should contain the first 10458 samples (as rows), with ROIs (cells) as columns. 
#Your extinction_traces array should contain the remaining (10459 through the final sample) samples (as rows), with ROIs (cells) as columns.
conditioning_traces = fear_traces[0:10458,:]
extinction_traces = fear_traces[10459:,:]

[[0.15983534 0.41501203 0.3902705  ... 0.35204699 0.48097605 0.62691492]
 [0.16923594 0.42458029 0.41144669 ... 0.34330168 0.48668911 0.60960583]
 [0.16266296 0.42059838 0.41282583 ... 0.3496634  0.50390474 0.60653214]
 ...
 [0.32861473 0.28751125 0.26240167 ... 0.37736194 0.37567386 0.50740489]
 [0.32794533 0.28163828 0.25274062 ... 0.36408747 0.37959856 0.50357071]
 [0.32512022 0.28986587 0.26196723 ... 0.35587041 0.39239762 0.50929452]]
[[0.32379705 0.26254674 0.2404604  ... 0.39995322 0.43074039 0.55675584]
 [0.32134975 0.26630658 0.24682864 ... 0.40661194 0.417479   0.54582627]
 [0.31833945 0.26721986 0.25068323 ... 0.39903295 0.4323318  0.51594392]
 ...
 [0.10190191 0.13573    0.10133815 ... 0.37895831 0.42750513 0.44738347]
 [0.10574757 0.16318269 0.11586664 ... 0.38334589 0.41140551 0.44590861]
 [0.09936723 0.14104242 0.11517277 ... 0.39657268 0.41661691 0.4648573 ]]


In [19]:
#In a new Code Cell, print the size of your conditioning_traces and extinction_traces arrays.
print(conditioning_traces.shape) #did this here so I could see how many ROIs there were
print(extinction_traces.shape)
print(conditioning_traces.size)
print(extinction_traces.size)

(10458, 63)
(14209, 63)
658854
895167


In [15]:
len(conditioning_traces)
10458/15

697.2

In [16]:
len(extinction_traces)
14209/15

947.2666666666667

In [17]:
#In a new Code Cell, make time_conditioning and time_extinction variables, corresponding to time during the conditioning session, 
#and time during the extinction session, respectively. The sampling rate for the miniscope used to capture these data was 15 fps. 
#Use this information to make your variables, which should both start at "0", end at the total length of the recording session (in seconds), 
#and have a length equal to the number of samples for each session.
time_conditioning = (0,697.2,10458) #10458/15 is the length of the recording session divided by the frames per second to get samples per session
time_extinction = (0,947.27,14209)

In a new Markdown Cell, state the number of ROIs (cells) that were imaged during these sessions, and the total length of time, both in seconds, and in minutes, of the conditioning and extinction sessions.

There are 63 ROIs because that is the y value when you plug in the shape. The total length of time for time_conditioning was 10458 seconds or 174.3 minutes. The total length of time for time_extinction was 14209 seconds or 236.81667 minutes. 

In [ ]:
#In a new Code Cell, plot the first and second ROIs (columns) from your conditioning_traces variable in one subplot. 
#Plot the first and second ROIs from your extinction_traces variable in a second subplot. Make the first ROI blue, and the second ROI red in each subplot. 
#Put time on the x-axis of both subplots.
# Make vertical black lines at shock onset (3 total), and vertical green lines at tone onset (3 total) in your first subplot. Label your axes.
